In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size = 10000

In [4]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4603, 6578, 1532, 9555],
 [4603, 6578, 1532, 6526],
 [4603, 6361, 1532, 5122],
 [4633, 4619, 4014, 2976, 1228],
 [4633, 4619, 4014, 2976, 9589],
 [9269, 4603, 4894, 1532, 2952],
 [5833, 7768, 2351, 2976]]

In [ ]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

## pad_sequences will add zeros in the starting or ending of the sentence

In [6]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sen_length)
print(embedded_docs)

##padding = pre means add zeros at the starting
##padding = post means add zeros at the last

[[   0    0    0    0 4603 6578 1532 9555]
 [   0    0    0    0 4603 6578 1532 6526]
 [   0    0    0    0 4603 6361 1532 5122]
 [   0    0    0 4633 4619 4014 2976 1228]
 [   0    0    0 4633 4619 4014 2976 9589]
 [   0    0    0 9269 4603 4894 1532 2952]
 [   0    0    0    0 5833 7768 2351 2976]]


In [11]:
## Feature representation
dim = 10 ## means i want 10 features with respect to the dimensions

In [13]:
model = Sequential()
model.add(Embedding(voc_size, dim,input_length = sent_length))
model.compile('adam', 'mse')

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 217ms/step


array([[[ 1.81684010e-02, -1.51557922e-02, -9.48865339e-03,
          2.08106078e-02, -3.97794247e-02, -5.89348003e-03,
         -2.36298572e-02,  1.71049573e-02, -1.10052712e-02,
         -4.23280858e-02],
        [ 1.81684010e-02, -1.51557922e-02, -9.48865339e-03,
          2.08106078e-02, -3.97794247e-02, -5.89348003e-03,
         -2.36298572e-02,  1.71049573e-02, -1.10052712e-02,
         -4.23280858e-02],
        [ 1.81684010e-02, -1.51557922e-02, -9.48865339e-03,
          2.08106078e-02, -3.97794247e-02, -5.89348003e-03,
         -2.36298572e-02,  1.71049573e-02, -1.10052712e-02,
         -4.23280858e-02],
        [ 1.81684010e-02, -1.51557922e-02, -9.48865339e-03,
          2.08106078e-02, -3.97794247e-02, -5.89348003e-03,
         -2.36298572e-02,  1.71049573e-02, -1.10052712e-02,
         -4.23280858e-02],
        [-4.03671749e-02,  2.85130478e-02, -2.16073915e-03,
         -3.74988317e-02, -1.83589086e-02, -1.13423951e-02,
          3.77906486e-03, -4.37427647e-02, -3.443907

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 4603, 6578, 1532, 9555])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 120ms/step


array([[ 0.0181684 , -0.01515579, -0.00948865,  0.02081061, -0.03977942,
        -0.00589348, -0.02362986,  0.01710496, -0.01100527, -0.04232809],
       [ 0.0181684 , -0.01515579, -0.00948865,  0.02081061, -0.03977942,
        -0.00589348, -0.02362986,  0.01710496, -0.01100527, -0.04232809],
       [ 0.0181684 , -0.01515579, -0.00948865,  0.02081061, -0.03977942,
        -0.00589348, -0.02362986,  0.01710496, -0.01100527, -0.04232809],
       [ 0.0181684 , -0.01515579, -0.00948865,  0.02081061, -0.03977942,
        -0.00589348, -0.02362986,  0.01710496, -0.01100527, -0.04232809],
       [-0.04036717,  0.02851305, -0.00216074, -0.03749883, -0.01835891,
        -0.0113424 ,  0.00377906, -0.04374276, -0.03443908,  0.03650324],
       [ 0.03652659,  0.01046843, -0.03544689,  0.00647726,  0.02589114,
         0.02574405, -0.01176244, -0.00625895, -0.01474822, -0.02172065],
       [ 0.01280749, -0.01207735, -0.01372013, -0.04700359,  0.04525018,
         0.02461978, -0.01053099,  0.00685881